name: iotgw-discovery
version: '1.1'
summary: IOT Gateway discovery manager snap 
description: discovery application
confinement: strict
grade: devel
architectures: [armhf]
environment:
  LD_LIBRARY_PATH: "$LD_LIBRARY_PATH:$SNAP/lib"
  LD_LIBRARY_PATH: "$SNAP_LIBRARY_PATH:$LD_LIBRARY_PATH"
  NODE_PATH: $SNAP/lib/node_modules
apps:
  iotgw-discovery:
    command: "iotgw-discovery"
    plugs: [network, snapd-control]
parts:
  iotgw-discovery:
    plugin: nodejs
    node-engine: "8.12.0"
    node-package-manager: yarn
    source: .
    build-packages:
      - python
      - g++
      - make
