name: iotgw-discovery
version: '1.0'
summary: IOT Gateway discovery manager snap 
description: discovery application
confinement: strict
architectures: [armhf]
parts:
  iotgw-discovery:
    plugin: nodejs
    node-engine: "8.12.0"
    source: .
apps:
  iotgw-discovery:
    command: "bin/iotgw-discovery"
    daemon: simple
    restart-condition: always
    plugs: [network, network-control, snapd-control]
