name: iotgw-discovery
version: '1.1'
summary: IOT Gateway discovery manager snap 
description: discovery application
confinement: devmode
grade: devel

environment:
  LD_LIBRARY_PATH: "$LD_LIBRARY_PATH:$SNAP/lib"
  LD_LIBRARY_PATH: "$SNAP_LIBRARY_PATH:$LD_LIBRARY_PATH"
  NODE_PATH: $SNAP/lib/node_modules

parts:
  iotgw-discovery:
    plugin: nodejs
    node-engine: "8.12.0"
    node-package-manager: yarn
    source: .
    build-packages:
      - python
      - g++
      - make
apps:
  iotgw-discovery:
    command: "bin/iotgw-discovery"
    daemon: simple
    plugs: [network, snapd-control]

architectures: [armhf amd64]
