name: iotgw-discovery
version: '1.1'
summary: IOT Gateway discovery manager snap 
description: discovery application
confinement: strict
grade: devel
architectures: [armhf]
apps:
  iotgw-discovery:
    command: "iotgw-discovery"
    plugs: [network, snapd-control]
parts:
  iotgw-discovery:
    plugin: nodejs
    node-engine: "8.12.0"
    source: .
